const palette = [
    {
        paletteName: 'Test1',
        id: 'test1',
        emoji: '😎',
        colors: [
            { name: 'Black', color: '#000000' },
            { name: 'Maroon', color: '#800000' },
            { name: 'Green', color: '#008000' },
            { name: 'Olive', color: '#808000' },
            { name: 'Navy', color: '#000080' },
            { name: 'Purple', color: '#800080' },
            { name: 'Teal', color: '#008080' },
            { name: 'Silver', color: '#c0c0c0' },
            { name: 'Grey', color: '#808080' },
            { name: 'Red', color: '#ff0000' },
            { name: 'Lime', color: '#00ff00' },
            { name: 'Yellow', color: '#ffff00' },
            { name: 'Blue', color: '#0000ff' },
            { name: 'Fuchsia', color: '#ff00ff' },
            { name: 'Aqua', color: '#00ffff' },
            { name: 'White', color: '#ffffff' },
            { name: 'DarkGreen', color: '#005f00' },
            { name: 'DeepSkyBlue4', color: '#005f5f' },
            { name: 'DodgerBlue2', color: '#005fff' },
        ]
    },
    {
        paletteName: 'Test2',
        id: 'test2',
        emoji: '😊',
        colors: [
            { name: 'CG Blue1', color: '#277DA1' },
            { name: 'Queen Blue', color: '#577590' },
            { name: 'Cadet Blue', color: '#4D908E' },
            { name: 'Zomp', color: '#43AA8B' },
            { name: 'Pistachio', color: '#90BE6D' },
            { name: 'Maize Crayola', color: '#F9C74F' },
            { name: 'Mango Tango', color: '#F9844A' },
            { name: 'Yellow Orange Color Wheel', color: '#F8961E' },
            { name: 'Orange Red', color: '#F3722C' },
            { name: 'Red Salsa', color: '#F94144' },
            { name: 'Platinum', color: '#E5E5E5' },
            { name: 'CG Blue2', color: '#0081A7' },
            { name: 'Light Yellow', color: '#FDFCDC' },
            { name: 'Peach Puff', color: '#FED9B7' },
            { name: 'Bittersweet', color: '#F07167' },
            { name: 'Space Cadet', color: '#2B2D42' },
            { name: 'Manatee', color: '#8D99AE' },
            { name: 'Alice Blue', color: '#EDF2F4' },
            { name: 'Mango', color: '#FFBE0B' },
            { name: 'Blue Violet', color: '#8338EC' },
        ]
    },
    {
        paletteName: 'Test3',
        id: 'test3',
        emoji: '😊',
        colors: [
            { name: 'Black', color: '#000000' },
            { name: 'Maroon', color: '#800000' },
            { name: 'Green', color: '#008000' },
            { name: 'Olive', color: '#808000' },
            { name: 'Navy', color: '#000080' },
            { name: 'Purple', color: '#800080' },
            { name: 'Teal', color: '#008080' },
            { name: 'Silver', color: '#c0c0c0' },
            { name: 'Grey', color: '#808080' },
            { name: 'Red', color: '#ff0000' },
            { name: 'Lime', color: '#00ff00' },
            { name: 'Yellow', color: '#ffff00' },
            { name: 'Blue', color: '#0000ff' },
            { name: 'Fuchsia', color: '#ff00ff' },
            { name: 'Aqua', color: '#00ffff' },
            { name: 'White', color: '#ffffff' },
            { name: 'DarkGreen', color: '#005f00' },
            { name: 'DeepSkyBlue4', color: '#005f5f' },
            { name: 'DodgerBlue2', color: '#005fff' },
            { name: 'DarkRed', color: '#5f0000' },
        ]
    },
    {
        paletteName: 'Test4',
        id: 'test4',
        emoji: '😊',
        colors: [
            { name: 'CG Blue1', color: '#277DA1' },
            { name: 'Queen Blue', color: '#577590' },
            { name: 'Cadet Blue', color: '#4D908E' },
            { name: 'Zomp', color: '#43AA8B' },
            { name: 'Pistachio', color: '#90BE6D' },
            { name: 'Maize Crayola', color: '#F9C74F' },
            { name: 'Mango Tango', color: '#F9844A' },
            { name: 'Yellow Orange Color Wheel', color: '#F8961E' },
            { name: 'Orange Red', color: '#F3722C' },
            { name: 'Red Salsa', color: '#F94144' },
            { name: 'Platinum', color: '#E5E5E5' },
            { name: 'CG Blue2', color: '#0081A7' },
            { name: 'Light Yellow', color: '#FDFCDC' },
            { name: 'Peach Puff', color: '#FED9B7' },
            { name: 'Bittersweet', color: '#F07167' },
            { name: 'Space Cadet', color: '#2B2D42' },
        ]
    },
]

export default palette